---
title: "Data preprocessing"
output: html_document
---


## Directories

```{r }

if ((Sys.info()["nodename"]) == "COP026") {
  dir_data <- "C:/Users/arvor_d/Documents/workwork/data"
  dir_plot <- "C:/Users/arvor_d/Documents/workwork/plot"
} else if ((Sys.info()["nodename"]) == "COSTELSV6") {
  dir_data <- "F:/kamir_e/$data"
  dir_plot <- "F:/kamir_e/$plot "
}
jkhkjjkj

```

## Library

```{r }

library(plyr)
library(tidyverse)
library(tidyr)
library(dplyr)
library(foreach)
library(iterators)
library(lwgeom)
library(parallel)
library(doParallel)
library(maps)
library(nnet)
library(ggplot2)
library(latticeExtra)
library(sp)
library(rgdal)
library(raster)
library(stringi)
library(ggmap)
library(sf)
library(stars)
library(terra)

```

## HYDROBASINS: Cropping SHP to mato grosso extent

```{r }

# Mato Grosso border shapefile
mg_borders <- shapefile(file.path(dir_data, "boundaries","mato grosso", "mt84.shp"))

# Hydroshed hydrobasins at level 9
hydrobasins <- shapefile(file.path(dir_data, "hydroshed","hydrobasins_level9", "hybas_sa_lev09_v1c.shp"))

# Cropping 
hydrobasin_mg <- intersect(hydrobasins, mg_borders)

# Writing output shapefile
writeOGR(hydrobasin_mg, layer = "hydrobasin_mg_lev9", driver="ESRI Shapefile", dsn= file.path(dir_data, "hydroshed","hydrobasins_level9"), overwrite_layer = TRUE)

```

## PANGAEA: cropping on mato grosso extent

```{r }

# Loading
panga_braz84 <- rast(file.path(dir_data, "pangaea", "panga_braz84.tif"))

# Cropping 
panga_braz_mt <- crop(panga_braz84, vect(mg_borders))

# Writing output shapefile
writeRaster(panga_braz_mt, file = file.path(dir_data, "pangaea", "panga_braz84_mt.tif"))

```

## ELEVATION: cropping file to mato grosso extent

```{r }


# Mato Grosso border shapefile
mg_borders <- st_read(file.path(dir_data, "boundaries","mato grosso", "mt84.shp"))

# Elevation
elevation <- rast(file.path(dir_data, "hydroshed", "hydrocon elevation", "elevation_merge.tif"))

plot(elevation)
plot(mg_borders, add=TRUE)

# Cropping 
elevation_crop <- crop(elevation, vect(mg_borders))

plot(elevation_crop)
plot(mg_borders, add=TRUE)

# Writing output raster
writeRaster(elevation_crop, file = file.path(dir_data, "hydroshed", "hydrocon elevation", "elevation_crop.tif"))


```

## WATER SURFACES: cropping on hydrobasin extents

We crop and save each hydrobasin-cropped file

```{r }

### 1. LOADING HYDROBASINS ###

hydrobasins <- st_read(file.path(dir_data, "hydroshed","hydrobasins_level9","hydrobasin_mg_lev9.shp"))
hybas_id <- hydrobasins$HYBAS_ID


### 2. CROPPING FILES ON HYDORBASIN EXTENTS ###

  ## SIMPLE LINE STREAMS ##

  # hydrographic network on MG
hydronetwork <- st_read(file.path(dir_data, "water_surface", "rios_simples", "rios_simple84.shp"))
  
tictoc::tic()
  no_cores <- detectCores()
  cl <- makeCluster(no_cores) # setting up number of cores
  registerDoParallel(cl) # parallelizing on them
  
  foreach(i=hybas_id, .packages=c('sf')) %dopar%  { #
      ligne = which(hydrobasins$HYBAS_ID==i)
      # cropping single rivers on watershed level
    crop_list <- st_intersects(hydrobasins[ligne,],hydronetwork)
    crop_shp <- hydronetwork[unlist(crop_list),]
    st_write(crop_shp, file.path(dir_data, "water_surface", "rios_simples", paste0("riossimple_poly",i,".shp")), delete_layer = TRUE)
  
   }
  
  stopCluster(cl)
tictoc::toc() 
 
  ## POLY LINE STREAMS ##
  
  # poly-hydrographic network on MG
polynetwork <- st_read(file.path(dir_data, "water_surface", "rios_poly", "output_hidro_poly.shp"))
  
  no_cores <- detectCores()
  cl <- makeCluster(no_cores) # setting up number of cores
  registerDoParallel(cl) # parallelizing on them
  foreach(i=hybas_id, .packages=c('sf')) %dopar%  { #
      ligne = which(hydrobasins$HYBAS_ID==i)
      # cropping single rivers on watershed level
    crop_list <- st_intersects(hydrobasins[ligne,],polynetwork)
    poly_shp <- polynetwork[unlist(crop_list),]
    st_write(poly_shp, file.path(dir_data, "water_surface", "rios_poly", paste0("riospoly_poly",i,".shp")), delete_layer = TRUE)
  
   }
  
  stopCluster(cl)
  
  ## WATER RESERVOIRS ##
  
  #lake network on MG
  lago <- st_read(file.path(dir_data, "water_surface", "lago", "input_lago_reservatorio_icv.shp"))
  
  no_cores <- detectCores()
  cl <- makeCluster(no_cores) # setting up number of cores
  registerDoParallel(cl) # parallelizing on them
  
  foreach(i=hybas_id, .packages=c('sf')) %dopar%  { #
      ligne = which(hydrobasins$HYBAS_ID==i)
      # cropping single rivers on watershed level
    crop_list <- st_intersects(hydrobasins[ligne,],lago)
    lago_shp <- lago[unlist(crop_list),]
    st_write(lago_shp, file.path(dir_data, "water_surface", "lago", paste0("lago_poly",i,".shp")), delete_layer = TRUE)
  
   }
  
  stopCluster(cl)
  
  
  
  ## SOURCE ##
  
  # source network on MG
  nascente <- st_read(file.path(dir_data, "water_surface", "nascentes", "nascente84.shp"))
  
  no_cores <- detectCores()
  cl <- makeCluster(no_cores) # setting up number of cores
  registerDoParallel(cl) # parallelizing on them
  
  foreach(i=hybas_id, .packages=c('sf')) %dopar%  { #
       ligne = which(hydrobasins$HYBAS_ID==i)
     # cropping single rivers on watershed level
    crop_list <- st_intersects(hydrobasins[ligne,],nascente)
    nascente_shp <- nascente[unlist(crop_list),]
    st_write(nascente_shp, file.path(dir_data, "water_surface", "nascentes", paste0("source_poly",i,".shp")), delete_layer = TRUE)
  
   }
  
  stopCluster(cl)
  
  
```




