---
title: "Functions"
output: html_document
---

```{r }


if ((Sys.info()["nodename"]) == "COP026") {
  dir_data <- "C:/Users/arvor_d/Documents/workwork/data"
  dir_plot <- "C:/Users/arvor_d/Documents/workwork/plot"
} else if ((Sys.info()["nodename"]) == "COSTELSV6") {
  dir_data <- "F:/kamir_e/$data"
  dir_plot <- "F:/kamir_e/$plot "
}

```

## Library

```{r setup, include=FALSE}

library(plyr)
library(dplyr)
library(foreach)
library(iterators)
library(parallel)
library(doParallel)
library(maps)
library(nnet)
library(latticeExtra)
library(sp)
library(rgdal)
library(raster)
library(sf)
library(stars)
library(exactextractr)
library(tictoc)
library(terra)

```

## Extract raster value for each basin polygon, WITH PARALLEL PROCESSING

3% d'erreur surface


```{r }

basin_extract_parallel = function(landuse.rast, basin.sf){
  
  # we extract landuse cells from each basin polygon
  # first we crop the landuse raster on polygon extent
  # then we use extract function, which also gives cell fraction and coordinates
  # we save a list of data frame (1 df per polygon)
  
  hybas_id <- basin.sf$HYBAS_ID
  #list.extract<-list()
  
   no_cores <- detectCores()
   cl <- makeCluster(no_cores) # setting up number of cores
   registerDoParallel(cl) # parallelizing on them
   foreach(i = hybas_id, .packages=c('dplyr', 'terra')) %do%  { 

    ligne = which(basin.sf$HYBAS_ID==i)
    landuse_crop <- terra::crop(landuse.rast, basin.sf[ligne,], snap='out')
    
    df_extract <- terra::extract(landuse_crop,vect(basin.sf[ligne,]), exact=TRUE, xy=TRUE)

    df_export <- df_extract %>% mutate(poly.id=i) %>% rename(x=fraction,y=x,fraction=y)

    save(df_export, file = file.path(dir_data, "processed", paste0("extractbiom_",i,".RData")))
      }
  
  stopCluster(cl)
#  return(list.extract)
  
}




```


## Extract raster value for each basin polygon, NO PARALLEL PROCESSING



```{r }

basin_extract = function(landuse.rast, basin.sf){
  
  # we extract landuse cells from each basin polygon
  # first we crop the landuse raster on polygon extent
  # then we use extract function, which also gives cell fraction and coordinates
  # we save a list of data frame (1 df per polygon)
  
  hybas_id <- basin.sf$HYBAS_ID
 
  for(i in hybas_id)  { #, .packages=c('dplyr', 'terra')) %dopar%  { 

    ligne = which(basin.sf$HYBAS_ID==i)
    landuse_crop <- terra::crop(landuse.rast, basin.sf[ligne,], snap='out')
    
    df_extract <- terra::extract(landuse_crop,vect(basin.sf[ligne,]), exact=TRUE, xy=TRUE)

    df_export <- df_extract %>% mutate(poly.id=i) %>% rename(x=fraction,y=x,fraction=y)

    save(df_export, file = file.path(dir_data, "processed", paste0("extractbiom_",i,".RData")))

      }
  
}



```

## Crop+mask approche: faster and broader and no coordinates


```{r }

mb.f <- rast(file.path(dir_data, "processed", "biomas1985_2019_mg.tif"))
hydrobasin <- st_read(file.path(dir_data, "hydroshed","hydrobasins_level9", "hydrobasin_mg_lev9.shp"))
hydrobas.f <- hydrobasin[1000,]

# e <- extent()
strt = Sys.time()
system.time({
mb.bas <- terra::crop(mb.f, hydrobas.f)
})
system.time({
mb.bas.mask <- terra::mask(mb.bas, vect(hydrobas.f))
})
# plot(mb.bas.mask)
mb.bas.mask.mx = as.matrix(mb.bas.mask)
# table(mb.bas.mask.vc)*900/10000
Table.mx = apply(mb.bas.mask.mx,2,table)
Table.mx = lapply(Table.mx,function(x){x*900/10000})
# dev.new()
print(Sys.time()-strt)
```