---
title: "Mapping vulnerability features"
output: html_document
---

## Directories

```{r }

if ((Sys.info()["nodename"]) == "COP026") {
  dir_data <- "C:/Users/arvor_d/Documents/workwork/data"
  dir_plot <- "C:/Users/arvor_d/Documents/workwork/plot"
} else if ((Sys.info()["nodename"]) == "COSTELSV6") {
  dir_data <- "F:/kamir_e/$data"
  dir_plot <- "F:/kamir_e/$plots"
}

```

## Library

```{r }

library(plyr)
library(tidyverse)
library(tidyr)
library(dplyr)
library(ggplot2)
library(ggmap)
library(sf)
library(patchwork)


```

## PARAMETERS

Create a shapefile of randomly selected hydrobasin 
On which vulnerability has been computed

```{r }

hydrobasin <- st_read(file.path(dir_data, "hydroshed","hydrobasins_level9", "hydrobasin_mg_lev9.shp"))
load(file = file.path(dir_data, "vulnerability", "1000randomid.RData"))
y <- 2017


```

## PLOTTING FEATURES 

Create a shapefile of randomly selected hydrobasin 
On which vulnerability has been computed

```{r }

install.packages("rnaturalearth")
install.packages("rnaturalearthdata")
library(rnaturalearth)
library(rnaturalearthdata)


sf_y <- st_read(file.path(dir_data, "vulnerability", "yearly", paste0(y, "_whole_vulnerability.shp")))

world <- ne_countries(scale = "medium", returnclass = "sf")

ggmap(data=world)+
  geom_polygon(sf_y)
  
  
  
  
```









